//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caerostris.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caerostris.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        public static string AddedAt {
            get {
                return ResourceManager.GetString("AddedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved tracks history.
        /// </summary>
        public static string AddedAtGraphShortName {
            get {
                return ResourceManager.GetString("AddedAtGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved tracks history.
        /// </summary>
        public static string AddedAtGraphTitle {
            get {
                return ResourceManager.GetString("AddedAtGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} around {1}.
        /// </summary>
        public static string Around {
            get {
                return ResourceManager.GetString("Around", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTIST.
        /// </summary>
        public static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio feature.
        /// </summary>
        public static string AudioFeature {
            get {
                return ResourceManager.GetString("AudioFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio features.
        /// </summary>
        public static string AudioFeaturesGraphShortName {
            get {
                return ResourceManager.GetString("AudioFeaturesGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio features of your saved tracks over time (avg per month).
        /// </summary>
        public static string AudioFeaturesGraphTitle {
            get {
                return ResourceManager.GetString("AudioFeaturesGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect account.
        /// </summary>
        public static string AuthModalAccept {
            get {
                return ResourceManager.GetString("AuthModalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: to access the full functionality of this app, you&apos;ll need to connect a Spotify Premium account..
        /// </summary>
        public static string AuthModalNote {
            get {
                return ResourceManager.GetString("AuthModalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify authorization needed.
        /// </summary>
        public static string AuthModalTitle {
            get {
                return ResourceManager.GetString("AuthModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats per minute.
        /// </summary>
        public static string BeatsPerMinute {
            get {
                return ResourceManager.GetString("BeatsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t display this context.
        /// </summary>
        public static string CantDisplayContext {
            get {
                return ResourceManager.GetString("CantDisplayContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string ContextMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with Cærostris Insights.
        /// </summary>
        public static string CreatedWithCaerostrisInsights {
            get {
                return ResourceManager.GetString("CreatedWithCaerostrisInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        public static string Explicit {
            get {
                return ResourceManager.GetString("Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans also like.
        /// </summary>
        public static string FansAlsoLike {
            get {
                return ResourceManager.GetString("FansAlsoLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — with.
        /// </summary>
        public static string Feat {
            get {
                return ResourceManager.GetString("Feat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follower.
        /// </summary>
        public static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        public static string InsightsMenuItem {
            get {
                return ResourceManager.GetString("InsightsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LibraryMenuItem {
            get {
                return ResourceManager.GetString("LibraryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums, artists and playlists you add to your Listen Later list will appear here.
        /// </summary>
        public static string ListenLaterItemsWillAppearHere {
            get {
                return ResourceManager.GetString("ListenLaterItemsWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen later.
        /// </summary>
        public static string ListenLaterMenuItem {
            get {
                return ResourceManager.GetString("ListenLaterMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        public static string LoadingAlbum {
            get {
                return ResourceManager.GetString("LoadingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analytics.
        /// </summary>
        public static string LoadingAnalytics {
            get {
                return ResourceManager.GetString("LoadingAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        public static string LoadingArtist {
            get {
                return ResourceManager.GetString("LoadingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context.
        /// </summary>
        public static string LoadingContext {
            get {
                return ResourceManager.GetString("LoadingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string LoadingListenLater {
            get {
                return ResourceManager.GetString("LoadingListenLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist.
        /// </summary>
        public static string LoadingPlaylist {
            get {
                return ResourceManager.GetString("LoadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string LoadingTracks {
            get {
                return ResourceManager.GetString("LoadingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        public static string LoadingWhat {
            get {
                return ResourceManager.GetString("LoadingWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string MonthOfYear {
            get {
                return ResourceManager.GetString("MonthOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized score.
        /// </summary>
        public static string NormalizedScore {
            get {
                return ResourceManager.GetString("NormalizedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  saved tracks.
        /// </summary>
        public static string NumSavedTracks {
            get {
                return ResourceManager.GetString("NumSavedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1}.
        /// </summary>
        public static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback: {0}.
        /// </summary>
        public static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        public static string PlaybackMenuItem {
            get {
                return ResourceManager.GetString("PlaybackMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST.
        /// </summary>
        public static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        public static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular tracks.
        /// </summary>
        public static string PopularTracks {
            get {
                return ResourceManager.GetString("PopularTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchInputPlaceholder {
            get {
                return ResourceManager.GetString("SearchInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchMenuItem {
            get {
                return ResourceManager.GetString("SearchMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results will appear here.
        /// </summary>
        public static string SearchResultsWillAppearHere {
            get {
                return ResourceManager.GetString("SearchResultsWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, you should be getting redirected soon. Communicating with the Cærostris authorization server....
        /// </summary>
        public static string ShouldBeRedirectedSoon {
            get {
                return ResourceManager.GetString("ShouldBeRedirectedSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explicit.
        /// </summary>
        public static string ShowExplicitColumn {
            get {
                return ResourceManager.GetString("ShowExplicitColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter row.
        /// </summary>
        public static string ShowFilterRow {
            get {
                return ResourceManager.GetString("ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popularity.
        /// </summary>
        public static string ShowPopularityColumn {
            get {
                return ResourceManager.GetString("ShowPopularityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tracks.
        /// </summary>
        public static string ShowTracks {
            get {
                return ResourceManager.GetString("ShowTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tracks around this value.
        /// </summary>
        public static string ShowTracksAroundThisValue {
            get {
                return ResourceManager.GetString("ShowTracksAroundThisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song.
        /// </summary>
        public static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs with a duration of {0}.
        /// </summary>
        public static string SongsWithADurationOf {
            get {
                return ResourceManager.GetString("SongsWithADurationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs with {0} around {1}.
        /// </summary>
        public static string SongsWithPropertyAround {
            get {
                return ResourceManager.GetString("SongsWithPropertyAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs you saved in {0} {1}.
        /// </summary>
        public static string SongsYouSavedIn {
            get {
                return ResourceManager.GetString("SongsYouSavedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length.
        /// </summary>
        public static string TrackLengthGraphShortName {
            get {
                return ResourceManager.GetString("TrackLengthGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length distribution.
        /// </summary>
        public static string TrackLengthGraphTitle {
            get {
                return ResourceManager.GetString("TrackLengthGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
    }
}
