//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caerostris.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Caerostris.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuItem {
            get {
                return ResourceManager.GetString("AboutMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Cærostris.
        /// </summary>
        internal static string AboutSectionAbout {
            get {
                return ResourceManager.GetString("AboutSectionAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributions.
        /// </summary>
        internal static string AboutSectionAttributions {
            get {
                return ResourceManager.GetString("AboutSectionAttributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string AboutSectionHelp {
            get {
                return ResourceManager.GetString("AboutSectionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal.
        /// </summary>
        internal static string AboutSectionLegal {
            get {
                return ResourceManager.GetString("AboutSectionLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added.
        /// </summary>
        internal static string AddedAt {
            get {
                return ResourceManager.GetString("AddedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved tracks history.
        /// </summary>
        internal static string AddedAtGraphShortName {
            get {
                return ResourceManager.GetString("AddedAtGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved tracks history.
        /// </summary>
        internal static string AddedAtGraphTitle {
            get {
                return ResourceManager.GetString("AddedAtGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} around {1}.
        /// </summary>
        internal static string Around {
            get {
                return ResourceManager.GetString("Around", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARTIST.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string Artists {
            get {
                return ResourceManager.GetString("Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio feature.
        /// </summary>
        internal static string AudioFeature {
            get {
                return ResourceManager.GetString("AudioFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio features.
        /// </summary>
        internal static string AudioFeaturesGraphShortName {
            get {
                return ResourceManager.GetString("AudioFeaturesGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio features of your saved tracks over time (avg per month).
        /// </summary>
        internal static string AudioFeaturesGraphTitle {
            get {
                return ResourceManager.GetString("AudioFeaturesGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect account.
        /// </summary>
        internal static string AuthModalAccept {
            get {
                return ResourceManager.GetString("AuthModalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: to access the full functionality of this app, you&apos;ll need to connect a Spotify Premium account. Cærostris places cookies in your browser to enable Spotify authorization. 
        ///
        ///All of your data stays on your device, with the single exception of an authorization token that may be sent to the Cærostris authorization server. You can revoke this token at any time in your Spotify account settings. 
        ///
        ///Cærostris uses the Spotify Playback SDK to play music in the browser, which loads Google Analytics. To preven [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AuthModalNote {
            get {
                return ResourceManager.GetString("AuthModalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotify authorization needed.
        /// </summary>
        internal static string AuthModalTitle {
            get {
                return ResourceManager.GetString("AuthModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats per minute.
        /// </summary>
        internal static string BeatsPerMinute {
            get {
                return ResourceManager.GetString("BeatsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t display this context.
        /// </summary>
        internal static string CantDisplayContext {
            get {
                return ResourceManager.GetString("CantDisplayContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string ContextMenuItem {
            get {
                return ResourceManager.GetString("ContextMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Spotify link.
        /// </summary>
        internal static string CopySpotifyUrl {
            get {
                return ResourceManager.GetString("CopySpotifyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created with Cærostris Insights.
        /// </summary>
        internal static string CreatedWithCaerostrisInsights {
            get {
                return ResourceManager.GetString("CreatedWithCaerostrisInsights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing&apos;s playing..
        /// </summary>
        internal static string CurrentTrackUnavailable {
            get {
                return ResourceManager.GetString("CurrentTrackUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cærostris is not affiliated, associated, authorized, endorsed by or in any way officially connected to Spotify.
        ///The Spotify Platform, Spotify Service, Spotify Content and any Spotify Marks are the property of Spotify or Spotify’s licensors and protected by intellectual property rights..
        /// </summary>
        internal static string Disclaimers {
            get {
                return ResourceManager.GetString("Disclaimers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit.
        /// </summary>
        internal static string Explicit {
            get {
                return ResourceManager.GetString("Explicit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fans also like.
        /// </summary>
        internal static string FansAlsoLike {
            get {
                return ResourceManager.GetString("FansAlsoLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — with.
        /// </summary>
        internal static string Feat {
            get {
                return ResourceManager.GetString("Feat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follower.
        /// </summary>
        internal static string Follower {
            get {
                return ResourceManager.GetString("Follower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to followers.
        /// </summary>
        internal static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        internal static string InsightsMenuItem {
            get {
                return ResourceManager.GetString("InsightsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cærostris is an open source, experimental Blazor WebAssembly Spotify PWA client. Find out more at .
        /// </summary>
        internal static string Introduction {
            get {
                return ResourceManager.GetString("Introduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the project&apos;s GitHub page..
        /// </summary>
        internal static string IntroductionRepo {
            get {
                return ResourceManager.GetString("IntroductionRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string LibraryMenuItem {
            get {
                return ResourceManager.GetString("LibraryMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums, artists and playlists you add to your Listen Later list will appear here.
        /// </summary>
        internal static string ListenLaterItemsWillAppearHere {
            get {
                return ResourceManager.GetString("ListenLaterItemsWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listen later.
        /// </summary>
        internal static string ListenLaterMenuItem {
            get {
                return ResourceManager.GetString("ListenLaterMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to album.
        /// </summary>
        internal static string LoadingAlbum {
            get {
                return ResourceManager.GetString("LoadingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to analytics.
        /// </summary>
        internal static string LoadingAnalytics {
            get {
                return ResourceManager.GetString("LoadingAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artist.
        /// </summary>
        internal static string LoadingArtist {
            get {
                return ResourceManager.GetString("LoadingArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to context.
        /// </summary>
        internal static string LoadingContext {
            get {
                return ResourceManager.GetString("LoadingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingEllipsis {
            get {
                return ResourceManager.GetString("LoadingEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        internal static string LoadingListenLater {
            get {
                return ResourceManager.GetString("LoadingListenLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playlist.
        /// </summary>
        internal static string LoadingPlaylist {
            get {
                return ResourceManager.GetString("LoadingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        internal static string LoadingTracks {
            get {
                return ResourceManager.GetString("LoadingTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}.
        /// </summary>
        internal static string LoadingWhat {
            get {
                return ResourceManager.GetString("LoadingWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out anyway.
        /// </summary>
        internal static string LogoutModalAccept {
            get {
                return ResourceManager.GetString("LogoutModalAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: your Listen Later list will also be deleted. Once deleted, there is no way to recover it..
        /// </summary>
        internal static string LogoutModalNote {
            get {
                return ResourceManager.GetString("LogoutModalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogoutModalTitle {
            get {
                return ResourceManager.GetString("LogoutModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can control the playback with the &apos;play/pause&apos;, &apos;previous track&apos; and &apos;next track&apos; media buttons..
        /// </summary>
        internal static string MediaControls {
            get {
                return ResourceManager.GetString("MediaControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media controls.
        /// </summary>
        internal static string MediaControlsTitle {
            get {
                return ResourceManager.GetString("MediaControlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthOfYear {
            get {
                return ResourceManager.GetString("MonthOfYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized score.
        /// </summary>
        internal static string NormalizedScore {
            get {
                return ResourceManager.GetString("NormalizedScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  saved tracks.
        /// </summary>
        internal static string NumSavedTracks {
            get {
                return ResourceManager.GetString("NumSavedTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1}.
        /// </summary>
        internal static string OutOf {
            get {
                return ResourceManager.GetString("OutOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as: {0}.
        /// </summary>
        internal static string Playback {
            get {
                return ResourceManager.GetString("Playback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback.
        /// </summary>
        internal static string PlaybackMenuItem {
            get {
                return ResourceManager.GetString("PlaybackMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST.
        /// </summary>
        internal static string Playlist {
            get {
                return ResourceManager.GetString("Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popularity.
        /// </summary>
        internal static string Popularity {
            get {
                return ResourceManager.GetString("Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular tracks.
        /// </summary>
        internal static string PopularTracks {
            get {
                return ResourceManager.GetString("PopularTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchInputPlaceholder {
            get {
                return ResourceManager.GetString("SearchInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchMenuItem {
            get {
                return ResourceManager.GetString("SearchMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results will appear here.
        /// </summary>
        internal static string SearchResultsWillAppearHere {
            get {
                return ResourceManager.GetString("SearchResultsWillAppearHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait, you should be getting redirected soon. Communicating with the Cærostris authorization server....
        /// </summary>
        internal static string ShouldBeRedirectedSoon {
            get {
                return ResourceManager.GetString("ShouldBeRedirectedSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explicit.
        /// </summary>
        internal static string ShowExplicitColumn {
            get {
                return ResourceManager.GetString("ShowExplicitColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter row.
        /// </summary>
        internal static string ShowFilterRow {
            get {
                return ResourceManager.GetString("ShowFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popularity.
        /// </summary>
        internal static string ShowPopularityColumn {
            get {
                return ResourceManager.GetString("ShowPopularityColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tracks.
        /// </summary>
        internal static string ShowTracks {
            get {
                return ResourceManager.GetString("ShowTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tracks around this value.
        /// </summary>
        internal static string ShowTracksAroundThisValue {
            get {
                return ResourceManager.GetString("ShowTracksAroundThisValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song.
        /// </summary>
        internal static string Song {
            get {
                return ResourceManager.GetString("Song", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs with a duration of {0}.
        /// </summary>
        internal static string SongsWithADurationOf {
            get {
                return ResourceManager.GetString("SongsWithADurationOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs with {0} around {1}.
        /// </summary>
        internal static string SongsWithPropertyAround {
            get {
                return ResourceManager.GetString("SongsWithPropertyAround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs you saved in {0} {1}.
        /// </summary>
        internal static string SongsYouSavedIn {
            get {
                return ResourceManager.GetString("SongsYouSavedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stallman was right..
        /// </summary>
        internal static string StallmanWasRight {
            get {
                return ResourceManager.GetString("StallmanWasRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a column title: sort by the column / change the sort direction of the column.
        ///Shift + click on a column title: select additional columns to sort by / change sort direction of the column.
        ///Ctrl + click on a column title: reset current sort settings.
        ///Right click on a row: show context menu..
        /// </summary>
        internal static string TrackGridControls {
            get {
                return ResourceManager.GetString("TrackGridControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrackGrid controls.
        /// </summary>
        internal static string TrackGridControlsTitle {
            get {
                return ResourceManager.GetString("TrackGridControlsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length.
        /// </summary>
        internal static string TrackLengthGraphShortName {
            get {
                return ResourceManager.GetString("TrackLengthGraphShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track length distribution.
        /// </summary>
        internal static string TrackLengthGraphTitle {
            get {
                return ResourceManager.GetString("TrackLengthGraphTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        internal static string Tracks {
            get {
                return ResourceManager.GetString("Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
